name: Build/test suite

on:
  push:
    branches:
      mainline
  pull_request:
    branches:
      mainline

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
          - os: macos-latest
          - os: windows-latest

    name: |
      test ${{ matrix.os }}

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out project
        uses: actions/checkout@v4

      - name: Install Linux dependencies
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          sudo apt install libmpfr-dev libeigen3-dev

      - name: Install MacOS dependencies
        if: startsWith(matrix.os, 'macos')
        run: |
          brew install mpfr catch2 eigen

      - name: CMake configure and build
        uses: threeal/cmake-action@v2.0.0
        with:
          options: |
            XPREC_BUILD_TESTING=${{ startsWith(matrix.os, 'windows') && 'OFF' || 'ON' }}
          run-build: true

      - name: Run tests
        if: (!startsWith(matrix.os, 'windows'))
        run: |
          build/test/tests
